name: CI

on:
  pull_request:
    branches: '*'
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Format code
        run: dart format --line-length 120 --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze
      # Skip tests for now
      # - name: Run tests
      #   run: dart test
